### ISSUE TITLE
Install it locally  (by project)

### ISSUE THREAD

**Issue by Schlickmann** [kunalpanchal/secure-env#5]
Hi there,

Is there any way to install it locally in my project? 
I have tried yarn add secure-env and then when I try to execute from the root folder of my project I get the message below.

```
$ secure-env .env -s mySecret
bash: secure-env: command not found
```

**Comment by kunalpanchal** [comment]
Hey @Schlickmann, `secure-env cli` needs to be installed globally so that it is available on your terminal anywhere. For globally installing the package run:

```
yarn global add secure-env
secure-env .env -s mySecret
```

If you surely need to run it locally from your project root you need to run this command: 

```bash
./node_modules/secure-env/dist/es5/lib/cli.js .env -s mySecret
```

Please do let me know if you are still facing any issues.

**Comment by Schlickmann** [comment]
@kunalpanchal thank you very much :)
